services:
  frontend:
    build:
      context: ./frontend/heart-disease-predictor
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres-db
    networks:
      - app-network

  ai:
    build:
      context: ./ai_module
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - postgres-db
    networks:
      - app-network

  postgres-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
